OCAMLMAKEFILE = ../OCamlMakefile

INCDIRS = +camlp4

THREADS = yes

SOURCES = m_range.mli m_range.ml \
	m_profile.mli m_profile.ml \
	m_metaprofile.mli m_metaprofile.ml \
	m_profile_stream.mli m_profile_stream.ml \
	m_delta.mli m_delta.ml \
	m_delta_builder.mli m_delta_builder.ml \
	m_make.mli m_make.ml \
	m_translate.mli m_translate.ml \
	m_untranslate.mli m_untranslate.ml \
	m_xmfa.mli m_xmfa.ml \
	m_maf.mli m_maf.ml \
	m_profiles_cli.ml

RESULT  = mugsy_profiles

PACKS = core_extended str seq ocaml_bio

-include $(OCAMLMAKEFILE)
